// =============================================================================
// SLSA v1.0 build provenance + signing.
//
// References:
//   SLSA v1.0 spec — https://slsa.dev/spec/v1.0/provenance
//   in-toto Statement v1 (envelope) — https://github.com/in-toto/attestation
//   Sigstore cosign — production keyless signing path used in CI
//   FIPS 204 (ML-DSA) — fall-forward path when cosign is unavailable
//
// This module is the in-process SLSA builder. The CI workflow
// (.github/workflows/release.yml) calls cosign directly; this module
// exists so:
//   1. The SLSA v1.0 attestation shape is typed end-to-end and Zod-checked.
//   2. We can sign/verify provenance locally with the existing PQ signer
//      from sig.ts so unit tests do not need cosign on the runner.
//   3. The verify() function rejects every form of tampering: changed
//      subject, changed builder, changed digest, changed signature.
//
// SLSA L3 requirements satisfied by the workflow:
//   - Source: GitHub repo, signed commits enforced.
//   - Build: GitHub Actions hosted runner, isolated per-job ephemeral VM.
//   - Provenance: generated by the workflow per artefact, stored as a
//     workflow artifact and attached to the GitHub Release.
//   - Signed: cosign keyless (Fulcio CA + Rekor transparency log) on every
//     release tag.
// =============================================================================

import { sha256 } from "@noble/hashes/sha2.js";
import { z } from "zod";
import { makeMlDsa65Signer, ML_DSA_65_PK, ML_DSA_65_SIG } from "./sig.js";

const SLSA_PROVENANCE_TYPE = "https://slsa.dev/provenance/v1" as const;
const IN_TOTO_STATEMENT_TYPE = "https://in-toto.io/Statement/v1" as const;

export const ARTEFACT_DIGEST_HEX_LEN = 64;

export const SubjectSchema = z.object({
  name: z.string().min(1),
  digest: z.object({
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
  }),
});
export type Subject = z.infer<typeof SubjectSchema>;

export const BuildContextSchema = z.object({
  /** Repo identity — `${org}/${repo}`. */
  sourceRepo: z.string().min(1),
  /** Full commit SHA (40-char hex). */
  sourceRef: z.string().regex(/^[0-9a-f]{40}$/),
  /** Builder ID — typically a workflow URL pinned to a commit. */
  builderId: z.string().url(),
  /** SLSA build type — typically a workflow YAML URL. */
  buildType: z.string().url(),
  /** Reproducible-build epoch. */
  startedOn: z.string().datetime(),
  finishedOn: z.string().datetime(),
  /** invocation parameters (e.g. workflow inputs). */
  invocation: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
  /** Subjects = the artefact set this provenance covers. */
  subjects: z.array(SubjectSchema).min(1),
});
export type BuildContext = z.infer<typeof BuildContextSchema>;

export const SlsaPredicateSchema = z.object({
  buildDefinition: z.object({
    buildType: z.string(),
    externalParameters: z.record(z.string(), z.unknown()),
    internalParameters: z.record(z.string(), z.unknown()),
    resolvedDependencies: z.array(z.object({
      uri: z.string(),
      digest: z.object({ gitCommit: z.string() }),
    })),
  }),
  runDetails: z.object({
    builder: z.object({ id: z.string() }),
    metadata: z.object({
      invocationId: z.string(),
      startedOn: z.string().datetime(),
      finishedOn: z.string().datetime(),
    }),
  }),
});
export type SlsaPredicate = z.infer<typeof SlsaPredicateSchema>;

export const ProvenanceStatementSchema = z.object({
  _type: z.literal(IN_TOTO_STATEMENT_TYPE),
  predicateType: z.literal(SLSA_PROVENANCE_TYPE),
  subject: z.array(SubjectSchema).min(1),
  predicate: SlsaPredicateSchema,
});
export type ProvenanceStatement = z.infer<typeof ProvenanceStatementSchema>;

export const SignedProvenanceSchema = z.object({
  statement: ProvenanceStatementSchema,
  /** Hex-encoded ML-DSA-65 signature over the canonical-JSON statement. */
  signature: z.string().regex(/^[0-9a-f]+$/),
  /** Hex-encoded ML-DSA-65 public key the signature verifies under. */
  publicKey: z.string().regex(/^[0-9a-f]+$/),
  alg: z.literal("ML-DSA-65"),
});
export type SignedProvenance = z.infer<typeof SignedProvenanceSchema>;

export const ProvenanceVerdictSchema = z.object({
  ok: z.boolean(),
  reason: z.string().optional(),
});
export type ProvenanceVerdict = z.infer<typeof ProvenanceVerdictSchema>;

// -----------------------------------------------------------------------------
// Builder + signer
// -----------------------------------------------------------------------------

/**
 * Build a SLSA v1.0 provenance attestation for a build run. The output is
 * an in-toto Statement v1 envelope. The subject set is what gets digested
 * and identified at verify time.
 */
export function buildProvenance(ctx: BuildContext): ProvenanceStatement {
  const validated = BuildContextSchema.parse(ctx);
  const stmt: ProvenanceStatement = {
    _type: IN_TOTO_STATEMENT_TYPE,
    predicateType: SLSA_PROVENANCE_TYPE,
    subject: validated.subjects.map((s) => ({ name: s.name, digest: { sha256: s.digest.sha256 } })),
    predicate: {
      buildDefinition: {
        buildType: validated.buildType,
        externalParameters: validated.invocation,
        internalParameters: {
          repository: validated.sourceRepo,
          ref: validated.sourceRef,
        },
        resolvedDependencies: [
          {
            uri: `git+https://github.com/${validated.sourceRepo}@${validated.sourceRef}`,
            digest: { gitCommit: validated.sourceRef },
          },
        ],
      },
      runDetails: {
        builder: { id: validated.builderId },
        metadata: {
          invocationId: `${validated.builderId}#${validated.sourceRef}`,
          startedOn: validated.startedOn,
          finishedOn: validated.finishedOn,
        },
      },
    },
  };
  return ProvenanceStatementSchema.parse(stmt);
}

/**
 * Compute the canonical bytes the signer covers. Uses RFC 8785-style
 * canonicalisation: every object's keys are sorted lexicographically before
 * JSON.stringify. This makes the signature insensitive to key order in
 * incoming JSON.
 */
export function canonicaliseProvenance(stmt: ProvenanceStatement): Uint8Array {
  return new TextEncoder().encode(canonicalJson(stmt));
}

function canonicalJson(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error("non-finite numbers are not canonicalisable");
    return JSON.stringify(value);
  }
  if (typeof value === "string" || typeof value === "boolean") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (typeof value === "object") {
    const keys = Object.keys(value as Record<string, unknown>).sort();
    const parts: string[] = [];
    for (const k of keys) {
      parts.push(`${JSON.stringify(k)}:${canonicalJson((value as Record<string, unknown>)[k])}`);
    }
    return `{${parts.join(",")}}`;
  }
  throw new Error(`unsupported value of type ${typeof value}`);
}

export interface SignProvenanceInput {
  statement: ProvenanceStatement;
  publicKey: Uint8Array;
  secretKey: Uint8Array;
}

/** Sign a provenance statement with ML-DSA-65 (FIPS 204). */
export function signProvenance(input: SignProvenanceInput): SignedProvenance {
  const signer = makeMlDsa65Signer();
  if (input.publicKey.length !== ML_DSA_65_PK) {
    throw new Error(`publicKey must be ${ML_DSA_65_PK} bytes`);
  }
  const bytes = canonicaliseProvenance(input.statement);
  const sig = signer.sign(bytes, input.secretKey);
  return SignedProvenanceSchema.parse({
    statement: input.statement,
    signature: toHex(sig),
    publicKey: toHex(input.publicKey),
    alg: "ML-DSA-65",
  });
}

/**
 * Verify a signed provenance attestation.
 *
 * Returns ok=true only when:
 *   1. The signed envelope parses against the SLSA + in-toto schemas.
 *   2. The signature is well-formed (3309 bytes for ML-DSA-65).
 *   3. ML-DSA-65 verify(sig, canonical(statement), pubKey) succeeds.
 *   4. (When `expectedPublicKey` is supplied) the pinned public key matches.
 *
 * Any deviation — tampered subject, swapped digest, truncated sig — falls
 * through to ok=false with a one-line reason. Never throws.
 */
export function verifyProvenance(
  signed: SignedProvenance,
  expectedPublicKey?: Uint8Array,
): ProvenanceVerdict {
  const parse = SignedProvenanceSchema.safeParse(signed);
  if (!parse.success) {
    return { ok: false, reason: `schema:${parse.error.issues[0]?.message ?? "invalid"}` };
  }
  const env = parse.data;
  const sig = fromHex(env.signature);
  if (sig.length !== ML_DSA_65_SIG) {
    return { ok: false, reason: "signature-length" };
  }
  const pk = fromHex(env.publicKey);
  if (pk.length !== ML_DSA_65_PK) {
    return { ok: false, reason: "public-key-length" };
  }
  if (expectedPublicKey) {
    if (expectedPublicKey.length !== ML_DSA_65_PK) {
      return { ok: false, reason: "pinned-key-length" };
    }
    if (!bytesEqual(pk, expectedPublicKey)) {
      return { ok: false, reason: "pinned-key-mismatch" };
    }
  }
  const signer = makeMlDsa65Signer();
  const bytes = canonicaliseProvenance(env.statement);
  const ok = signer.verify(sig, bytes, pk);
  if (!ok) return { ok: false, reason: "signature-verify-failed" };
  return { ok: true };
}

// -----------------------------------------------------------------------------
// Helpers — subject digest
// -----------------------------------------------------------------------------

/** Compute the sha256 hex digest of an artefact. Used to populate `subject`. */
export function subjectFromBytes(name: string, bytes: Uint8Array): Subject {
  const hex = toHex(sha256(bytes));
  return SubjectSchema.parse({ name, digest: { sha256: hex } });
}

function toHex(bytes: Uint8Array): string {
  let s = "";
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i]!;
    s += (b < 16 ? "0" : "") + b.toString(16);
  }
  return s;
}

function fromHex(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error("odd-length hex string");
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = Number.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
    if (!Number.isFinite(byte)) throw new Error("invalid hex");
    out[i] = byte;
  }
  return out;
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let acc = 0;
  for (let i = 0; i < a.length; i++) acc |= a[i]! ^ b[i]!;
  return acc === 0;
}
